version: '3.7'

services:
  moviebasedb:
    image: mysql:8
    container_name: moviebasedb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: moviedb
      MYSQL_USER: movie
      MYSQL_PASSWORD: Admin123*
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql

# Names our volume
volumes:
  dbdata: